global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/alerting_rules.yml"

scrape_configs:
  - job_name: 'face-emotion-analyzer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'face-emotion-analyzer'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system-metrics'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'container-metrics'

  # OpenCVとGPU監視用の設定
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['gpu-exporter:9835']
        labels:
          service: 'gpu-metrics'