app:
  name: face-emotion-analyzer
  version: 1.0.0
  env: development
  debug: true

server:
  port: 8080
  host: localhost
  read_timeout: 5s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576

security:
  allowed_origins: http://localhost:8080,http://localhost:3000
  csrf_token_length: 32
  rate_limit:
    requests_per_minute: 1000
    burst: 100
  cors:
    allowed_methods:
      - GET
      - POST
      - OPTIONS
    allowed_headers:
      - Content-Type
      - X-CSRF-Token
      - Authorization
    max_age: 86400
  headers:
    strict_transport_security: max-age=31536000; includeSubDomains
    content_security_policy: >
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob:;
      media-src 'self' blob:;
      connect-src 'self'

image:
  max_size: 10485760
  allowed_types:
    - image/jpeg
    - image/png
  max_dimension: 4096
  quality: 90

opencv:
  cascade_file: haarcascade_frontalface_default.xml
  min_face_size: 30
  scale_factor: 1.1
  min_neighbors: 3
  flags: 0

logging:
  level: debug
  format: json
  output: stdout
  fields:
    service: face-analyzer
    version: 1.0.0
    environment: development

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  tracing_enabled: true
  profiling_enabled: true